src/JN/PlatformBundle/Entity/Image.php
<?php
namespace JN\PlatformBundle\Entity;


use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\UploadedFile;

/**

 * @ORM\Table(name="jn_image")

 * @ORM\Entity

 * @ORM\HasLifecycleCallbacks

 */
class Image

{

  /**

   * @ORM\Column(name="id", type="integer")

   * @ORM\Id

   * @ORM\GeneratedValue(strategy="AUTO")

   */

  private $id;


  /**

   * @ORM\Column(name="url", type="string", length=255)

   */

  private $url;


  /**

   * @ORM\Column(name="alt", type="string", length=255)

   */

  private $alt;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

  

   
 public $file;


  // On ajoute cet attribut pour y stocker le nom du fichier temporairement

  private $tempFilename;


  // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre

  public function setFile(UploadedFile $file)

  {

    $this->file = $file;


    // On vérifie si on avait déjà un fichier pour cette entité

    if (null !== $this->url) {

      // On sauvegarde l'extension du fichier pour le supprimer plus tard

      $this->tempFilename = $this->url;


      // On réinitialise les valeurs des attributs url et alt

      $this->url = null;

      $this->alt = null;

    }

  }


  /**

   * @ORM\PrePersist()

   * @ORM\PreUpdate()

   */

  public function preUpload()

  {

    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien

    if (null === $this->file) {

      return;

    }


    // Le nom du fichier est son id, on doit juste stocker également son extension

    // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »

    $this->url = $this->file->guessExtension();


    // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute

    $this->alt = $this->file->getClientOriginalName();

  }


  /**

   * @ORM\PostPersist()

   * @ORM\PostUpdate()

   */

  public function upload()

  {

    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien

    if (null === $this->file) {

      return;

    }


    // Si on avait un ancien fichier, on le supprime

    if (null !== $this->tempFilename) {

      $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;

      if (file_exists($oldFile)) {

        unlink($oldFile);

      }

    }


    // On déplace le fichier envoyé dans le répertoire de notre choix

    $this->file->move(

      $this->getUploadRootDir(), // Le répertoire de destination

      $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »

    );

  }


  /**

   * @ORM\PreRemove()

   */

  public function preRemoveUpload()

  {

    // On sauvegarde temporairement le nom du fichier, car il dépend de l'id

    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;

  }


  /**

   * @ORM\PostRemove()

   */

  public function removeUpload()

  {

    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé

    if (file_exists($this->tempFilename)) {

      // On supprime le fichier

      unlink($this->tempFilename);

    }

  }


  public function getUploadDir()

  {

    // On retourne le chemin relatif vers l'image pour un navigateur

    return 'uploads/img';

  }


  protected function getUploadRootDir()

  {

    // On retourne le chemin relatif vers l'image pour notre code PHP

    return __DIR__.'/../../../../web/'.$this->getUploadDir();

  }

  public function getWebPath()

  {

    return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();

  }
  
    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }
}

src/JN/PlatformBundle/Controller/AdvertController.php
<?php

namespace JN\PlatformBundle\Controller;

//important ces use
use JN\PlatformBundle\Form\ModificationPlaylistType;
use JN\PlatformBundle\Form\PlaylistType;
use JN\PlatformBundle\Entity\Musique;
use JN\PlatformBundle\Entity\Playlist;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

use Symfony\Component\Form\Extension\Core\Type\DateType;

use Symfony\Component\Form\Extension\Core\Type\FormType;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Component\Form\Extension\Core\Type\TextareaType;

use Symfony\Component\Form\Extension\Core\Type\TextType;



class AdvertController extends Controller

{
  public function indexAction($page)

  {
	if ($page < 1) {

      throw $this->createNotFoundException("La page ".$page." n'existe pas.");

    }


    
     $listPlaylist = $this->getDoctrine()

  ->getManager()

  ->getRepository('JNPlatformBundle:Playlist')

  ->findAll()



    ;


   

    return $this->render('JNPlatformBundle:Advert:index.html.twig', array(

      'listPlaylist' => $listPlaylist

    ));

  }

  public function viewAction($id)

  {
   
    $em = $this->getDoctrine()->getManager();

    $advert = $em->getRepository('JNPlatformBundle:Playlist')->find($id);



    if (null === $advert) {

      throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");

    }

    $listMusiques = $em

      ->getRepository('JNPlatformBundle:Musique')

      ->findBy(array('advert' => $advert))

    ;


    return $this->render('JNPlatformBundle:Advert:view.html.twig', array(

      'advert'           => $advert,

      'listMusiques' => $listMusiques,
    ));
 }



  public function addAction(Request $request)

  {

     

    $advert = new Playlist();

    $advert->setDate(new \Datetime());

   $form = $this->get('form.factory')->create(PlaylistType::class, $advert);


   


    if ($request->isMethod('POST')) {

      
      $form->handleRequest($request);
	



      if ($form->isValid()) {

      

        $em = $this->getDoctrine()->getManager();

        $em->persist($advert);

        $em->flush();
	


        $request->getSession()->getFlashBag()->add('notice', 'Annonce bien enregistrée.');



        return $this->redirectToRoute('jn_platform_view', array('id' => $advert->getId()));

      }

    }


    return $this->render('JNPlatformBundle:Advert:add.html.twig', array(

      'form' => $form->createView(),

    ));

  }
   
    



  public function editAction($id,Request $request)

  {

     $em = $this->getDoctrine()->getManager();


    $advert = $em->getRepository('JNPlatformBundle:Playlist')->find($id);


    if (null === $advert) {

      throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");

    }


    $form = $this->get('form.factory')->create(ModificationPlaylistType::class, $advert);


    if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

    
      $em->flush();


      $request->getSession()->getFlashBag()->add('notice', 'Annonce bien modifiée.');


      return $this->redirectToRoute('jn_platform_view', array('id' => $advert->getId()));

    }


    return $this->render('JNPlatformBundle:Advert:edit.html.twig', array(

      'advert' => $advert,

      'form'   => $form->createView(),

    ));

    }


   


  public function deleteAction(Request $request, $id)

  {
    $em = $this->getDoctrine()->getManager();


    $advert = $em->getRepository('JNPlatformBundle:Playlist')->find($id);


    if (null === $advert) {

      throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");

    }


    $form = $this->get('form.factory')->create();


    if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

      $em->remove($advert);

      $em->flush();


      $request->getSession()->getFlashBag()->add('info', "L'annonce a bien été supprimée.");


      return $this->redirectToRoute('jn_platform_home');

    }

    

    return $this->render('JNPlatformBundle:Advert:delete.html.twig', array(

      'advert' => $advert,

      'form'   => $form->createView(),

    ));

  }
  public function menuAction($limit)

  {

    $listPlaylists = $this->getDoctrine()

      ->getManager()

      ->getRepository('JNPlatformBundle:Playlist')

      ->findBy(

        array(),                

        array('date' => 'desc'), 

        $limit,                 

        0                       

    );


    return $this->render('JNPlatformBundle:Advert:menu.html.twig', array(

      'listPlaylists' => $listPlaylists

    ));

  }
  


}

src/JN/PlatformBundle/Resources/views/Advert/add.html.twig
{% extends "JNPlatformBundle::layout.html.twig" %}

{% block title %}

  Ajouter une musique - {{ parent() }}

{% endblock %}


{% block body %}


  <h2>Ajouter une musique</h2>


  {{ include("JNPlatformBundle:Advert:form.html.twig") }}


  <p>

    Attention : cette musique sera ajoutée directement

    sur la page d'accueil après validation du formulaire.

  </p>
  
  


{% endblock %}

src/JN/PlatformBundle/Resources/views/Advert/delete.html.twig
{% extends "JNPlatformBundle::layout.html.twig" %}


{% block title %}

  Supprimer une playlist - {{ parent() }}

{% endblock %}


{% block jnplatform_body %}


  <h2>Supprimer une playlist</h2>


  <p>

    Etes-vous certain de vouloir supprimer la playlist "{{ advert.title }}" ?

  </p>


  {# On met l'id de l'annonce dans la route de l'action du formulaire #}

  <form action="{{ path('jn_platform_delete', {'id': advert.id}) }}" method="post">

    <a href="{{ path('jn_platform_view', {'id': advert.id}) }}" class="btn btn-default">

      <i class="glyphicon glyphicon-chevron-left"></i>

      Retour à la playlist

    </a>

    {# Ici j'ai écrit le bouton de soumission à la main #}

    <input type="submit" value="Supprimer" class="btn btn-danger" />

    {# Ceci va générer le champ CSRF #}

    {{ form_rest(form) }}

  </form>


{% endblock %}

src/JN/PlatformBundle/Resources/views/Advert/edit.html.twig
{% extends "JNPlatformBundle::layout.html.twig" %}


{% block title %}

  Modifier la musique - {{ parent() }}

{% endblock %}


{% block jnplatform_body %}


  <h2>Modifier une musique</h2>


  {{ include("JNPlatformBundle:Advert:form.html.twig") }}


  


  <p>

    <a href="{{ path('jn_platform_view', {'id': advert.id}) }}" class="btn btn-default">

      <i class="glyphicon glyphicon-chevron-left"></i>

      Retour à la liste

    </a>

  </p>


{% endblock %}

src/JN/PlatformBundle/Resources/views/Advert/form.html.twig
<p class="text-warning">Suivez ces instructions pour ajouter la musique de votre choix!</p>



<div class="well">

 {{ form(form) }}

</div>

src/JN/PlatformBundle/Resources/views/Advert/index.html.twig
{% extends "JNPlatformBundle::layout.html.twig" %}


{% block title %}

  Accueil - {{ parent() }}

{% endblock %}


{% block jnplatform_body %}


  <h2>Liste des musiques</h2>


  <ul class="list-inline">

    {% for advert in listPlaylist %}
      
      <li>

        <a href="{{ path('jn_platform_view', {'id': advert.id}) }}">

           <img 

  src="{{ asset(advert.image.webPath) }}"

  alt="{{ advert.image.alt }}"
  width = "140"
  height = "140"

class="img-rounded"/> <br>
 <p class="text-center">{{ advert.title }} - {{ advert.artiste|upper }} </p>
        </a>

      </li>


 

       
    {% else %}

      <li>Pas (encore !) de playlist </li>

    {% endfor %}

  </ul>


{% endblock %}
 

src/JN/PlatformBundle/Resources/views/Advert/menu.html.twig
<!DOCTYPE HTML>


<ul class="nav nav-pills nav-stacked">

  {% for advert in listPlaylists %}

    <li>

      <a href="{{ path('jn_platform_view', {'id': advert.id}) }}">

        {{ advert.title }}

      </a>

    </li>

  {% endfor %}

</ul>

src/JN/PlatformBundle/Resources/views/Advert/view.html.twig
{% extends "JNPlatformBundle::layout.html.twig" %}


{% block title %}

  Musiques - {{ parent() }}

{% endblock %}


{% block jnplatform_body %}


  <h2>{{ advert.title }}</h2>

  <i>Ajouté par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>


  <div class="well">

    {{ advert.content }}

  </div>

  <img 

  src="{{ asset(advert.image.webPath) }}"

  alt="{{ advert.image.alt }}"
  width = "370"
  height = "310"

/>
  <p>

    <a href="{{ path('jn_platform_home') }}" class="btn btn-default">

      <i class="glyphicon glyphicon-chevron-left"></i>

      Retour à la liste

    </a>

    <a href="{{ path('jn_platform_edit', {'id': advert.id}) }}" class="btn btn-default">

      <i class="glyphicon glyphicon-edit"></i>

      Modifier 

    </a>

    <a href="{{ path('jn_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">

      <i class="glyphicon glyphicon-trash"></i>

      Supprimer la musique
    </a>

  </p>


{% endblock %}